In [2]:
import numpy as np

In [ ]:
ARRAY OPERATIONS

In [3]:
a1 = np.array([1,2,3,4])
a2 = np.array([6,7,8,9])
a1+a2

array([ 7,  9, 11, 13])

In [4]:
a1*a2

array([ 6, 14, 24, 36])

In [5]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444])

In [6]:
a1//a2

array([0, 0, 0, 0])

In [7]:
a1**a2

array([     1,    128,   6561, 262144])

In [ ]:
BROADCASTING

In [8]:
l = [10,20,30,40,50]
arr = np.array(l)

In [9]:
arr+10

array([20, 30, 40, 50, 60])

In [11]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [12]:
arr2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [ ]:
DEEP AND SHALLOW COPY

In [13]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [17]:
slice = a[:5]
slice = slice*10
slice

array([10, 20, 30, 40, 50])

In [19]:
a[4:6]*10

array([50, 60])

In [ ]:
MATRIX OPERATIONS

In [20]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[6,7]])

In [21]:
 A

array([[1, 2],
       [3, 4]])

In [30]:
B

array([[5, 6],
       [8, 9]])

In [24]:
A@B

array([[21, 24],
       [47, 54]])

In [31]:
np.dot(A,B)

array([[21, 24],
       [47, 54]])

In [32]:
A

array([[1, 2],
       [3, 4]])

In [33]:
B

array([[5, 6],
       [8, 9]])

In [34]:
B.T

array([[5, 8],
       [6, 9]])

In [ ]:
ADVANCE ARRAY MANIPULATION

In [ ]:
STACKING ARRAY

In [38]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [39]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [40]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
Spilliting Array

In [42]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [43]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [44]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [45]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [46]:
np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]