In [1]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [5]:
a = [1,2,3.6,"suraj"]
np.array(a)

array(['1', '2', '3.6', 'suraj'], dtype='<U32')

In [7]:
l = [[1,4,5],[2,9,4],[2,9,3]]
l

[[1, 4, 5], [2, 9, 4], [2, 9, 3]]

In [8]:
np.array(l)

array([[1, 4, 5],
       [2, 9, 4],
       [2, 9, 3]])

In [9]:
np.arange(1,21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [11]:
arr = np.arange(5,51,5)
arr

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [14]:
zero = np.zeros(6)
zero

array([0., 0., 0., 0., 0., 0.])

In [15]:
zero = np.zeros((6,6))
zero

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
arr = np.ones((5,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [17]:
arr = np.linspace(1,2,100)
arr

array([1.        , 1.01010101, 1.02020202, 1.03030303, 1.04040404,
       1.05050505, 1.06060606, 1.07070707, 1.08080808, 1.09090909,
       1.1010101 , 1.11111111, 1.12121212, 1.13131313, 1.14141414,
       1.15151515, 1.16161616, 1.17171717, 1.18181818, 1.19191919,
       1.2020202 , 1.21212121, 1.22222222, 1.23232323, 1.24242424,
       1.25252525, 1.26262626, 1.27272727, 1.28282828, 1.29292929,
       1.3030303 , 1.31313131, 1.32323232, 1.33333333, 1.34343434,
       1.35353535, 1.36363636, 1.37373737, 1.38383838, 1.39393939,
       1.4040404 , 1.41414141, 1.42424242, 1.43434343, 1.44444444,
       1.45454545, 1.46464646, 1.47474747, 1.48484848, 1.49494949,
       1.50505051, 1.51515152, 1.52525253, 1.53535354, 1.54545455,
       1.55555556, 1.56565657, 1.57575758, 1.58585859, 1.5959596 ,
       1.60606061, 1.61616162, 1.62626263, 1.63636364, 1.64646465,
       1.65656566, 1.66666667, 1.67676768, 1.68686869, 1.6969697 ,
       1.70707071, 1.71717172, 1.72727273, 1.73737374, 1.74747

In [ ]:
Random Generation Function

In [19]:
np.random.rand(15)

array([0.62762427, 0.36458642, 0.40571196, 0.39090698, 0.55698052,
       0.22596367, 0.40695893, 0.750075  , 0.29457257, 0.33498517,
       0.54473343, 0.31314882, 0.48495511, 0.53521292, 0.61417335])

In [23]:
np.random.randn(15)

array([-2.48002559, -0.19871237, -0.43709067, -0.28176387,  1.0801094 ,
       -1.74180529, -0.62175843, -0.73099456,  0.8759327 , -2.32578788,
       -0.12485744,  0.10278345, -2.14153583, -0.61482157,  1.29546333])

In [28]:
np.random.randint(9)

3

In [ ]:
np.random.randint()